#pragma once

enum ResourceImage{
	//ロード画面
	IMAGE_LOAD_TITLE,
	IMAGE_LOAD_LOADING,
	IMAGE_LOAD_GAUGE_EMPTY,
	IMAGE_LOAD_GAUGE_FILL,
	IMAGE_LOAD_START,

	//メイン画面
	IMAGE_TITLE_CURSOR,
	IMAGE_TITLE_PRACTICE,
	IMAGE_TITLE_PRACTICE_DESCRIPTION,
	IMAGE_TITLE_RESULT,
	IMAGE_TITLE_RESULT_DESCRIPTION,
	IMAGE_TITLE_CONFIG,
	IMAGE_TITLE_CONFIG_DESCRIPTION,
	IMAGE_TITLE_MANUAL,
	IMAGE_TITLE_MANUAL_DESCRIPTION,
	IMAGE_TITLE_EXIT,
	IMAGE_TITLE_EXIT_DESCRIPTION,

	//レベル選択画面
	IMAGE_TITLE_PRACTICE_LEVEL_BEGINNER,
	IMAGE_TITLE_PRACTICE_LEVEL_STANDARD,
	IMAGE_TITLE_PRACTICE_LEVEL_HARD,
	IMAGE_TITLE_PRACTICE_LEVEL_DESCRIPTION,

	//リザルト画面
	IMAGE_TITLE_RESULT_DISPLAY_DESCRIPTION,

	//コンフィグ画面
	IMAGE_TITLE_CONFIG_BGM,
	IMAGE_TITLE_CONFIG_SE,
	IMAGE_TITLE_CONFIG_BACK,
	IMAGE_TITLE_CONFIG_DISPLAY_DESCRIPTION,

	//マニュアル画面
	IMAGE_TITLE_MANUAL_PAGE1,
	IMAGE_TITLE_MANUAL_PAGE2,
	IMAGE_TITLE_MANUAL_PAGE3,
	IMAGE_TITLE_MANUAL_PAGE4,
	IMAGE_TITLE_MANUAL_DESPLAY_DESCRIPTION,

	//ゲーム開始画面
	IMAGE_PRACTICE_BACKGROUND,
	IMAGE_PRACTICE_MAGIC_D,
	IMAGE_PRACTICE_MAGIC_C,
	IMAGE_PRACTICE_MAGIC_B,
	IMAGE_PRACTICE_MAGIC_A,
	IMAGE_PRACTICE_MAGIC_S,
	IMAGE_PRACTICE_STAR_RED,
	IMAGE_PRACTICE_STAR_GREEN,
	IMAGE_PRACTICE_STAR_YELLOW,
	IMAGE_PRACTICE_STAR_WHITE,

	IMAGE_UNKNOWN
};

enum ResourceSound{
	SOUND_BGM_TITLE,
	SOUND_BGM_STAGE,

	SOUND_SE_OK,
	SOUND_SE_CANCEL,
	SOUND_SE_MOVE,
	SOUND_SE_BLOCK_COLLIDE,
	SOUND_UNKNOWN
};

class IResourceManager
{
public:
	virtual ~IResourceManager() = 0;
	virtual int GetGraphicsHandle(ResourceImage eImage) = 0;
	virtual int GetSoundsHandle(ResourceSound eSound) = 0;
	virtual int GetGraphicsLoadingCount() = 0;
	virtual int GetSoundsLoadingCount() = 0;
	virtual int IsLoadGraphics() = 0;
	virtual int IsLoadSounds() = 0;
	virtual void SetSoundsBGMVolume(int nPercent) = 0;
	virtual void SetSoundsSEVolume(int nPercent) = 0;
};

