#pragma once

enum ResourceImage{
	//ゲームロード画面
	IMAGE_LOAD_BAR,
	IMAGE_LOAD_ZERO,
	IMAGE_LOAD_ONE,
	IMAGE_LOAD_TWO,
	IMAGE_LOAD_THREE,
	IMAGE_LOAD_FOUR,
	IMAGE_LOAD_FIVE,
	IMAGE_LOAD_SIX,
	IMAGE_LOAD_SEVEN,
	IMAGE_LOAD_EIGHT,
	IMAGE_LOAD_NINE,
	IMAGE_LOAD_DOT,
	IMAGE_LOAD_PERCENT,

	//ゲームタイトル画面
	IMAGE_TITLE_SCREEN,

	//メイン画面
	IMAGE_TITLE_CURSOR,
	IMAGE_TITLE_PRACTICE,
	IMAGE_TITLE_RESULT,
	IMAGE_TITLE_CONFIG,
	IMAGE_TITLE_EXIT,

	//レベル選択画面
	IMAGE_TITLE_PRACTICE_LEVEL_BEGINNER,
	IMAGE_TITLE_PRACTICE_LEVEL_STANDARD,
	IMAGE_TITLE_PRACTICE_LEVEL_HARD,

	//リザルト画面
	IMAGE_TITLE_RESULT_NO,
	IMAGE_TITLE_RESULT_NAME,
	IMAGE_TITLE_RESULT_SOUND,
	IMAGE_TITLE_RESULT_DAY,
	IMAGE_TITLE_RESULT_SCORE,
	IMAGE_TITLE_RESULT_JUDGE,
	IMAGE_TITLE_RESULT_WORD,

	//コンフィグ画面
	IMAGE_TITLE_CONFIG_BGM_VOLUME_BAR,
	IMAGE_TITLE_CONFIG_BGM_VOLUME_PERCENT,
	IMAGE_TITLE_CONFIG_SE,
	IMAGE_TITLE_CONFIG_SE_VOLUME_BAR,
	IMAGE_TITLE_CONFIG_SE_COLUME_PERCENT,
	IMAGE_TITLE_CONFIG_BACK,

	//ゲーム開始画面
	IMAGE_PRACTICE_BLOCK_AQUA,
	IMAGE_PRACTICE_BLOCK_BLACK,
	IMAGE_PRACTICE_BLOCK_BLUE,
	IMAGE_PRACTICE_BLOCK_GREEN,
	IMAGE_PRACTICE_BLOCK_ORANGE,
	IMAGE_PRACTICE_BLOCK_PAUPLE,
	IMAGE_PRACTICE_BLOCK_RED,
	IMAGE_PRACTICE_BLOCK_WHITE,
	IMAGE_PRACTICE_BLOCK_YELLOW,
	IMAGE_PRACTICE_SCORE,

	//ゲームポーズ画面
	IMAGE_PRACTICE_PAUSE,
	IMAGE_PRACTICE_PAUSE_DESCRIPTION,
	IMAGE_PRACTICE_PAUSE_YES,
	IMAGE_PRACTICE_PAUSE_NO,

	IMAGE_UNKNOWN
};

enum ResourceSound{
	SOUND_BGM_TITLE,
	SOUND_BGM_STAGE,

	SOUND_SE_OK,
	SOUND_SE_CANCEL,
	SOUND_SE_MOVE,
	SOUND_SE_BLOCK_COLLIDE,
	SOUND_SE_BLOCK_LINEPASS,
	SOUND_UNKNOWN
};

class IResourceManager
{
public:
	virtual ~IResourceManager() = 0;
	virtual int GetGraphicsHandle(ResourceImage eImage) = 0;
	virtual int GetSoundsHandle() = 0;
	virtual int GetGraphicsLoadingCount() = 0;
	virtual int GetSoundsLoadingCount() = 0;
	virtual int IsLoadGraphics() = 0;
	virtual int IsLoadSounds() = 0;
};

